export const AUDIO_ENCODING = {
    "AMR": "AMR",
    "AMR_WB": "AMR_WB",
    "ENCODING_UNSPECIFIED": "ENCODING_UNSPECIFIED",
    "FLAC": "FLAC",
    "LINEAR16": "LINEAR16",
    "MULAW": "MULAW",
    "OGG_OPUS": "OGG_OPUS",
    "SPEEX_WITH_HEADER_BYTE": "SPEEX_WITH_HEADER_BYTE",
    "UNRECOGNIZE": "UNRECOGNIZE",
}